name: Keep Scrapyd Awake

on:
  schedule:
    - cron: "*/12 * * * *"   # every 12 minutes
  workflow_dispatch:          # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Scrapyd Backends
        run: |
          echo "Pinging Scrapyd at $(date)"
          curl -s https://jobapp-backend-25kl.onrender.com/ || echo "Ping to jobapp-backend failed"
          curl -s https://jobapp-bah2.onrender.com/daemonstatus.json || echo "Ping to jobapp-bah2 failed"
